### ISSUE TITLE
optics not fully compatible with transport-level batching

### ISSUE THREAD

**Issue by glasser** [apollostack/optics-agent-js#47]
The optics agent instrumentation assumes only one query operation per HTTP request.

At the very least, this is implied where the schema-level resolve function takes its `info` and puts it in a single `info` slot on the HTTP-request-level `opticsContext` object.

There are two ways that this can be broken:
- Using apollo-client/server's transport-level batching, multiple "query documents" get sent on the same HTTP request
- You can always specify multiple "query operations" in one "query document". (Though, eg, react-apollo forbids this)

My guess is that the schema-level resolve function should add its info to a list on opticsContext. reportRequestEnd should iterate over them. reportRequestStart and reportTrace should be refactored to take the specific info they care about as a parameter rather than (or in addition to) the opticsContext.

This likely causes the issues we've seen where fields not mentioned in the query are sent to the optics backend as nodes.

**Comment by glasser** [comment]
Whoops, "multiple query operations per document" isn't actually a problem — while you can specify multiple queries in a document, you must still tell graphql which specific operation to run.  But transport-level batching is.

**Comment by glasser** [comment]
Note that this also means that durationHrTime is of *all queries on the request*.

**Comment by glasser** [comment]
So yeah — this opens a legit but real product question as to how we should treat transport-level batching, which might affect product UI, the protobuf, etc.

**Comment by n1mmy** [comment]
Here's the plan at the moment: for transport level batching, we report N separate queries (one for each in the batch) and each query with have the same start and end time (the start and end of the batch). Resolver timings will still be relative to the start of the query, which will be the same as the start of the batch. Thus, in the UX the user will see a trace with a long time line, and resolvers filling only a part of the timeline. This most accurately mirrors what is really going on, and means the measurement the optics product user sees correspond the the latencies visible to their users.

Unfortunately, this requires a change to `apollo-server`. There is currently no way to know which query an individual resolver execution corresponds to.

Step 1: submit a PR to `apollo-server` to add an `apolloBatchIndex: <Int>` field to the `context` object for each batched query.

Step 2: submit a PR to `optics-agent-js` to store a list of queries in `opticsContext` instead of a single query. Look at this new context field during `reportRequestStart` and during resolver wrapper execution and use it to bucket things appropriately . In `reportRequestEnd` process the whole list of queries.

**Comment by glasser** [comment]
I suggest chatting with @helfer to see if the batch transport protocol is
something we hope to see non Apollo GraphQL clients and servers adapt. If
so maybe the context object should not include the word "Apollo".

Does this call for an extra field in the protobuf too?

**Comment by stubailo** [comment]
I think many GraphQL servers will want _some_ kind of batching, so we will want to have a way for people to instrument their server for that.

**Comment by glasser** [comment]
I suggest also including a batchSize field or something (such that batchIndex ranges from 0 to batchSize-1). Maybe it's not necessary for the agent but if we're coming up with an informal protocol for telling graphql about transport batches, might as well include it.

**Comment by n1mmy** [comment]
@glasser Good idea! Will add `apolloBatchSize` as well as `apolloBatchIndex`

**Comment by n1mmy** [comment]
(including apollo in the namespace was @helfer 's call. If he changes his mind, I'm happy to change the PR =)
